### ISSUE TITLE
NPE when validating a certificate with no TrustAnchor

### ISSUE THREAD

**Issue by paulmillar** [eu-emi/canl-java#92] opened 2017-11-30 16:47 UTC
Hi,

One of our sites reported a problem with dCache.  The problem appears to be correlated with their upgrade of their trust-store to the latest IGTF release v1.88.

The problems were due to CRL processing; specifically in the processCRLF method in org.bouncycastle.jce.provider.RFC3280CertPathUtilities; however, the stack-trace (unfortunately) is based on a BouncyCastle jar file that has had the debugging information stripped out, so the exact line number that caused the problem is unknown.

The site also reported:  "It’s possibly a Java bug since it also seems to be hitting Argus and possible voms, cream and storm. Restarting the dCache domains has fixed the problems for me though."

So my initial theory was that this is some race-condition, triggered by the reload.  However, a (admittedly non-exhaustive) scan through the CANL-java and BC code failed to yield any likely candidates for such a race-condition.

Here is the stack-trace:

```
Caused by: java.lang.NullPointerException: null
        at org.bouncycastle.jce.provider.RFC3280CertPathUtilities.processCRLF(Unknown Source) ~[bcprov-jdk15on-1.50.jar:1.50.0]
        at eu.emi.security.authn.x509.helpers.pkipath.bc.RFC3280CertPathUtilitiesHelper.processCRLF2(RFC3280CertPathUtilitiesHelper.java:540) ~[canl-2.1.2.jar:2.1.2]
        at eu.emi.security.authn.x509.helpers.pkipath.bc.RFC3280CertPathUtilitiesHelper.checkCRL(RFC3280CertPathUtilitiesHelper.java:288) ~[canl-2.1.2.jar:2.1.2]
        at eu.emi.security.authn.x509.helpers.pkipath.bc.RFC3280CertPathUtilitiesHelper.checkCRLs2(RFC3280CertPathUtilitiesHelper.java:135) ~[canl-2.1.2.jar:2.1.2]
        at eu.emi.security.authn.x509.helpers.pkipath.bc.CRLRevocationChecker.checkRevocation(CRLRevocationChecker.java:49) ~[canl-2.1.2.jar:2.1.2]
        at eu.emi.security.authn.x509.helpers.pkipath.bc.FixedBCPKIXCertPathReviewer.checkRevocation(FixedBCPKIXCertPathReviewer.java:1746) ~[canl-2.1.2.jar:2.1.2]
        at eu.emi.security.authn.x509.helpers.pkipath.bc.FixedBCPKIXCertPathReviewer.checkSignatures(FixedBCPKIXCertPathReviewer.java:739) ~[canl-2.1.2.jar:2.1.2]
        at eu.emi.security.authn.x509.helpers.pkipath.bc.FixedBCPKIXCertPathReviewer.doChecks(FixedBCPKIXCertPathReviewer.java:218) ~[canl-2.1.2.jar:2.1.2]
        at org.bouncycastle.x509.PKIXCertPathReviewer.getErrors(Unknown Source) ~[bcprov-jdk15on-1.50.jar:1.50.0]
        at eu.emi.security.authn.x509.helpers.pkipath.BCCertPathValidator.checkNonProxyChain(BCCertPathValidator.java:309) ~[canl-2.1.2.jar:2.1.2]
        at eu.emi.security.authn.x509.helpers.pkipath.BCCertPathValidator.validate(BCCertPathValidator.java:152) ~[canl-2.1.2.jar:2.1.2]
        at eu.emi.security.authn.x509.helpers.pkipath.AbstractValidator.validate(AbstractValidator.java:129) ~[canl-2.1.2.jar:2.1.2]
        at eu.emi.security.authn.x509.impl.OpensslCertChainValidator.validate(OpensslCertChainValidator.java:227) ~[canl-2.1.2.jar:2.1.2]
        at org.dcache.util.CachingCertificateValidator$1.call(CachingCertificateValidator.java:92) ~[dcache-common-2.16.39.jar:2.16.39]
        at org.dcache.util.CachingCertificateValidator$1.call(CachingCertificateValidator.java:88) ~[dcache-common-2.16.39.jar:2.16.39]
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4793) ~[guava-19.0.jar:na]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542) ~[guava-19.0.jar:na]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323) ~[guava-19.0.jar:na]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286) ~[guava-19.0.jar:na]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201) ~[guava-19.0.jar:na]
        ... 27 common frames omitted
```

Cheers,

Paul.

**Comment by andreaceccanti** [comment] 2017-11-30 17:17
Hi Paul, 

probably you want to have a look at this GGUS ticket:

https://ggus.eu/index.php?mode=ticket_info&ticket_id=132205

**Comment by paulmillar** [comment] 2017-11-30 17:20
Thanks Andrea.

As it happens, I've already added a short section about dCache there.

Note that dCache is using BouncyCastle v1.50, which includes the bug-fix that Robert describes.  However, there's still the possibility that there are other bugs.

The odd part of this is that simply restarting dCache seems to have fixed the problem.

Cheers,

Paul.

**Comment by paulmillar** [comment] 2017-12-05 10:09
Recreated the problem, but this time with BC libraries compiled with debug information.  Here's the corresponding stack-trace:

```
Caused by: java.lang.NullPointerException: null
        at org.bouncycastle.jce.provider.RFC3280CertPathUtilities.processCRLF(RFC3280CertPathUtilities.java:486) ~[bcprov-jdk15on-1.50.jar:1.50.0]
        at eu.emi.security.authn.x509.helpers.pkipath.bc.RFC3280CertPathUtilitiesHelper.processCRLF2(RFC3280CertPathUtilitiesHelper.java:540) ~[canl-2.1.2.jar:2.1.2]
        at eu.emi.security.authn.x509.helpers.pkipath.bc.RFC3280CertPathUtilitiesHelper.checkCRL(RFC3280CertPathUtilitiesHelper.java:288) ~[canl-2.1.2.jar:2.1.2]
        at eu.emi.security.authn.x509.helpers.pkipath.bc.RFC3280CertPathUtilitiesHelper.checkCRLs2(RFC3280CertPathUtilitiesHelper.java:135) ~[canl-2.1.2.jar:2.1.2]
        at eu.emi.security.authn.x509.helpers.pkipath.bc.CRLRevocationChecker.checkRevocation(CRLRevocationChecker.java:49) ~[canl-2.1.2.jar:2.1.2]
        at eu.emi.security.authn.x509.helpers.pkipath.bc.FixedBCPKIXCertPathReviewer.checkRevocation(FixedBCPKIXCertPathReviewer.java:1746) ~[canl-2.1.2.jar:2.1.2]
        at eu.emi.security.authn.x509.helpers.pkipath.bc.FixedBCPKIXCertPathReviewer.checkSignatures(FixedBCPKIXCertPathReviewer.java:739) ~[canl-2.1.2.jar:2.1.2]
        at eu.emi.security.authn.x509.helpers.pkipath.bc.FixedBCPKIXCertPathReviewer.doChecks(FixedBCPKIXCertPathReviewer.java:218) ~[canl-2.1.2.jar:2.1.2]
        at org.bouncycastle.x509.PKIXCertPathReviewer.getErrors(PKIXCertPathReviewer.java:222) ~[bcprov-jdk15on-1.50.jar:1.50.0]
        at eu.emi.security.authn.x509.helpers.pkipath.BCCertPathValidator.checkNonProxyChain(BCCertPathValidator.java:309) ~[canl-2.1.2.jar:2.1.2]
        at eu.emi.security.authn.x509.helpers.pkipath.BCCertPathValidator.validate(BCCertPathValidator.java:152) ~[canl-2.1.2.jar:2.1.2]
        at eu.emi.security.authn.x509.helpers.pkipath.AbstractValidator.validate(AbstractValidator.java:129) ~[canl-2.1.2.jar:2.1.2]
        at eu.emi.security.authn.x509.impl.OpensslCertChainValidator.validate(OpensslCertChainValidator.java:227) ~[canl-2.1.2.jar:2.1.2]
        at org.dcache.util.CachingCertificateValidator$1.call(CachingCertificateValidator.java:92) ~[dcache-common-3.0.4.jar:3.0.4]
        at org.dcache.util.CachingCertificateValidator$1.call(CachingCertificateValidator.java:88) ~[dcache-common-3.0.4.jar:3.0.4]
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4793) ~[guava-19.0.jar:na]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542) ~[guava-19.0.jar:na]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323) ~[guava-19.0.jar:na]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286) ~[guava-19.0.jar:na]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201) ~[guava-19.0.jar:na]
        ... 28 common frames omitted
```

**Comment by paulmillar** [comment] 2017-12-05 10:31
I've identified that the NPE is caused by `RFC3280CertPathUtilities#processCRLF` being called by canl-java's 
RFC3280CertPathUtilitiesHelper#processCRLF2 with a `null` value for `defaultCRLSignCert`.

**Comment by msalle** [comment] 2017-12-05 11:30
Hi Paul
note that that's the same as what Robert found in https://ggus.eu/index.php?mode=ticket_info&ticket_id=132205#update#21 for an older version of BC used by VOMS. Are you sure it's the `defaultCRLSignCert` that's null, not the `signingCert` ? Robert thought that wouldn't give an NPE but just false.

**Comment by paulmillar** [comment] 2017-12-05 11:53
Here's the diff of the deployed version:
```
+++ b/prov/src/main/java/org/bouncycastle/jce/provider/RFC3280CertPathUtilities.java
@@ -460,8 +460,25 @@ protected static Set processCRLF(
         try
         {
             coll = CertPathValidatorUtilities.findCertificates(selector, paramsPKIX.getStores());
-            coll.addAll(CertPathValidatorUtilities.findCertificates(selector, paramsPKIX.getAdditionalStores()));
-            coll.addAll(CertPathValidatorUtilities.findCertificates(selector, paramsPKIX.getCertStores()));
+            for (Object o : coll) {
+                if (o == null) {
+                    System.err.println("Found null in paramsPKIX.getStores() reply");
+                }
+            }
+            Collection additionalStores = CertPathValidatorUtilities.findCertificates(selector, paramsPKIX.getAdditionalStores());
+            coll.addAll(additionalStores);
+            for (Object o : additionalStores) {
+                if (o == null) {
+                    System.err.println("Found null in paramsPKIX.getAdditionalStores() reply");
+                }
+            }
+            Collection getCertStores = CertPathValidatorUtilities.findCertificates(selector, paramsPKIX.getCertStores());
+            coll.addAll(getCertStores);
+            for (Object o : getCertStores) {
+                if (o == null) {
+                    System.err.println("Found null in paramsPKIX.getCertStores() reply");
+                }
+            }
         }
         catch (AnnotatedException e)
         {
@@ -469,6 +486,9 @@ protected static Set processCRLF(
         }
 
         coll.add(defaultCRLSignCert);
+        if (defaultCRLSignCert == null) {
+            System.err.println("Found null in defaultCRLSignCert");
+        }
 
         Iterator cert_it = coll.iterator();
 
@@ -1125,7 +1145,7 @@ protected static PKIXPolicyNode processCertE(
     {
         List certs = certPath.getCertificates();
         X509Certificate cert = (X509Certificate)certs.get(index);
-        // 
+        //
         // (e)
         //
         ASN1Sequence certPolicies = null;
paul@celebrimbor:~/git/bc-java ((r1rv50))$ 
```

The output from dCache:
```
[root@dcache-se-atlas03 ~]# grep Found\ null\ in /var/log/dcache/srm-dcache-se-atlas03Domain.log                                                                                                             
Found null in defaultCRLSignCert
Found null in defaultCRLSignCert
Found null in defaultCRLSignCert
Found null in defaultCRLSignCert
Found null in defaultCRLSignCert
Found null in defaultCRLSignCert
[root@dcache-se-atlas03 ~]#                                                                                                                                                                                  ```

**Comment by paulmillar** [comment] 2017-12-05 12:10
This seems to correspond to `workingPublicKey` being `null` in FixedBCPKIXCertPathReviewer#checkSignatures.

This possibility is guarded against in `checkSignatures` when verifying the signature (a call to CertPathValidatorUtilities#verifyX509Certificate), with the alternative code-path logging error and continuing; however, no such check protects a call to `checkRevocation` with a `null` value.

Note that the problem also seems to come from CRL checking, when processing CrlDistributionPoint in the certificate.

The canl-java unit test TestKSValidators#testNonSelfSignedTA also exercises this code-path with `workingPublicKey` being `null`; however, it doesn't trigger the bug because the certificate does not have any CrlDistributionPoints.

This still leaves open the question of why workingPublicKey is null.

**Comment by paulmillar** [comment] 2017-12-05 14:43
Some further information -- I applied the following patch to canl-java:

```
diff --git a/src/main/java/eu/emi/security/authn/x509/helpers/pkipath/bc/FixedBCPKIXCertPathReviewer.java b/src/main/java/eu/emi/security/authn/x509/helpers/pkipath/bc/FixedBCPKIXCertPathReviewer.java
index cb7f974..10ce9d0 100644
--- a/src/main/java/eu/emi/security/authn/x509/helpers/pkipath/bc/FixedBCPKIXCertPathReviewer.java
+++ b/src/main/java/eu/emi/security/authn/x509/helpers/pkipath/bc/FixedBCPKIXCertPathReviewer.java
@@ -612,10 +612,16 @@ private void checkSignatures()
             if (sign != null)
             {
                 workingPublicKey = sign.getPublicKey();
+                if (workingPublicKey == null) {
+                    System.err.println("FixedBCPKIXCertPathReviewer#checkSignatures recieved null workingPublicKey from sign#getPublicKey");
+                }
             }
             else
             {
                 workingPublicKey = trust.getCAPublicKey();
+                if (workingPublicKey == null) {
+                    System.err.println("FixedBCPKIXCertPathReviewer#checkSignatures recieved null workingPublicKey from trust#getCAPublicKey");
+                }
             }
 
             try
@@ -628,6 +634,10 @@ private void checkSignatures()
                 addError(msg);
             }
 
+        } else {
+            if (workingPublicKey == null) {
+                    System.err.println("FixedBCPKIXCertPathReviewer#checkSignatures null workingPublicKey not updated as trust == null");
+            }
         }
 
         // Basic cert checks
@@ -1722,6 +1732,9 @@ private void checkSignatures()
                    X509Certificate sign,
                    PublicKey workingPublicKey) throws SimpleValidationErrorException
     {
+           if (workingPublicKey == null) {
+               throw new NullPointerException("workingPublicKey is null");
+           }
            RevocationParameters params = paramsPKIX.getRevocationParams();
            CRLRevocationChecker crlChecker = new CRLRevocationChecker(paramsPKIX, validDate,
                            workingPublicKey, certs, params.getCrlCheckingMode());
```

With this version of canl-java deployed, dCache yielded the following output:

```
FixedBCPKIXCertPathReviewer#checkSignatures null workingPublicKey not updated as trust == null
05 Dec 2017 15:25:00 (SRM-dcache-se-atlas03) [] 
java.lang.RuntimeException: java.lang.NullPointerException: workingPublicKey is null
        at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1476) ~[na:1.8.0_121]
        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535) ~[na:1.8.0_121]
        [...]
```

This confirms that `checkRevocation` method is being called with a `workingPublicKey` value of `null`.  It also points to `getTrustAnchors(cert,pkixParams.getTrustAnchors())` either returning either more than one entry or no entries, or that something is throwing CertPathReviewerException before `trust` is assigned a value.

**Comment by msalle** [comment] 2017-12-06 12:52
Hi Paul, others,
From looking at [FixedBCPKIXCertPathReviewer.java#L653-L686](https://github.com/eu-emi/canl-java/blob/canl-2.1.2/src/main/java/eu/emi/security/authn/x509/helpers/pkipath/bc/FixedBCPKIXCertPathReviewer.java#L653-L686) I would say that `workingPublicKey` may only be legitimately be `null` for a self-signed (i.e. root) CA cert. In that case, revocation makes no sense: who should have revoked it? The 'else' clause in [line 684](https://github.com/eu-emi/canl-java/blob/canl-2.1.2/src/main/java/eu/emi/security/authn/x509/helpers/pkipath/bc/FixedBCPKIXCertPathReviewer.java#L684) seems to mean that the trust anchor is missing but should have been present. I think also in that case, it cannot check revocation, since presumably there won't be a CRL of a CA for which the actual PEM is not there. So I think that calling `checkRevocation()` (in line [line 739](https://github.com/eu-emi/canl-java/blob/canl-2.1.2/src/main/java/eu/emi/security/authn/x509/helpers/pkipath/bc/FixedBCPKIXCertPathReviewer.java#L739)) on a `null` `workingPublicKey` is probably not wanted since it cannot succeed. Not sure if it should be a fatal error, it still is a problem that the issuer cert isn't there or couldn't be found, in this case probably due to the cert roll-over.

**Comment by paulmillar** [comment] 2017-12-06 17:41
The problem that triggers this behaviour is now understood.  A fix is available here:

    https://github.com/eu-emi/canl-java/pull/93

However, this issue is with canl-java throwing a NPE, rather than providing a reasonable error message.

The fix itself is likely trivial (e.g., just don't call checkRevocation if workingPublicKey is null), however the checkSignatures method is hugely complicated and I don't really know what is the intended behaviour. 

Therefore I'd be grateful if someone else could fix this issue.

Someone with deep knowledge of X.509 and this code-base should

**Comment by golbi** [comment] 2019-02-20 18:36
@paulmillar I tend to close this one. The root cause should be fixed under the other bug and pull request. Regarding error reporting - I'm happy to improve it, however I'd need some reproducible test scenario to trigger this NPE. So if you have such case please add, I'll reopen this one.

**Closed by golbi** 2019-02-20 18:36 UTC
